# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  ruby: circleci/ruby@2.1.1

jobs:
  build_and_test:
    parameters:
      ruby-version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test:
          include: spec/**/*_spec.rb

workflows:
  build_and_test:
    jobs:
      - build_and_test:
          matrix:
              parameters:
                ruby-version: ["2.6", "2.7", "3.0", "3.1"]
